# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
        #volumes:
        #- ./pgdata:/var/lib/postgresql/data/pgdata

  ap:
    image: adminer
    build:
      context: .
      dockerfile: crud/Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
